const products = [
    { id: 1, name: "Procesador Intel i3", price: 160000, category:"processor", description:"Productividad y entretenimiento, todo disponible en tu computadora de escritorio. La superioridad tecnológica de INTEL es un beneficio para todo tipo de profesionales. Asegura el mejor rendimiento de las aplicaciones, de la transferencia de datos y la conexión con otros elementos tecnológicos.", image: "https://http2.mlstatic.com/D_NQ_NP_671623-MLA54687847194_032023-O.webp"},
    { id: 2, name: "Procesador Intel i5", price: 230000, category:"processor", description:"En este producto, encontrarás los núcleos, que son los encargados de ejecutar las instrucciones y actividades que le asignás a tu dispositivo. Estos tienen relación directa con dos elementos: los hilos y el modelo. Por lo tanto, a la hora de elegir un procesador, es importante que valores los tres en su conjunto.", image: "https://http2.mlstatic.com/D_NQ_NP_859509-MLU73213842167_122023-O.webp"},
    { id: 3, name: "Procesador Intel i7", price: 400000, category:"processor", description:"El Intel Core i7-12700F es compatible con los zócalos FCLGA1700 y admite tanto memorias RAM DDR4 como DDR5, lo que te permite elegir la mejor opción para tu sistema. Con un tamaño máximo de memoria RAM soportada de 128 GB, tendrás la capacidad necesaria para ejecutar aplicaciones exigentes y disfrutar de una experiencia de juego fluida.", image: "https://http2.mlstatic.com/D_NQ_NP_960803-MLU70044930468_062023-O.webp"},
    { id: 4, name: "Tarjeta Gráfica NVIDIA GTX 1080", price: 330000, category:"videoCard", description:"Tarjeta gráfica NVIDIA GTX 1080 de alto rendimiento, ideal para gaming y edición. Con 8GB GDDR5X, ofrece gráficos nítidos y fluidez en juegos AAA. Compatible con VR y soporta resoluciones 4K. Perfecta para entusiastas del rendimiento y creadores de contenido.", image: "https://http2.mlstatic.com/D_NQ_NP_928140-MLB25873293517_082017-O.webp"},
    { id: 5, name: "Tarjeta Gráfica NVIDIA RTX 2080", price: 620000, category:"videoCard", description:"Tarjeta gráfica NVIDIA RTX 2080 con 8GB GDDR6, diseñada para gaming de última generación y aplicaciones de IA. Con tecnología Ray Tracing y DLSS, ofrece gráficos ultrarrealistas y alto rendimiento en 4K. Ideal para gamers y creadores de contenido que buscan lo mejor en potencia y eficiencia.", image: "https://http2.mlstatic.com/D_NQ_NP_869238-MLU54957418809_042023-O.webp"},
    { id: 6, name: "Tarjeta Gráfica NVIDIA RTX 3080", price: 980000, category:"videoCard", description:"Tarjeta gráfica NVIDIA RTX 3080 con 10GB GDDR6X, perfecta para gaming extremo y creación de contenido 4K. Cuenta con Ray Tracing de segunda generación y DLSS para un rendimiento fluido y gráficos hiperrealistas. Ideal para entusiastas que buscan rendimiento de vanguardia en los títulos más exigentes.", image: "https://http2.mlstatic.com/D_NQ_NP_748274-MLU74977413814_032024-O.webp"},
    { id: 7, name: "Tarjeta Gráfica NVIDIA RTX 4080", price: 2200000, category:"videoCard", description:"Tarjeta gráfica NVIDIA RTX 4080 con 16GB GDDR6X, la elección definitiva para gaming 4K y trabajo creativo de alto rendimiento. Con Ray Tracing avanzado y DLSS 3, ofrece una experiencia visual y de rendimiento inigualable. Ideal para quienes buscan estar a la vanguardia de la tecnología gráfica.", image: "https://http2.mlstatic.com/D_NQ_NP_782697-MLU69821067861_062023-O.webp"},
    { id: 8, name: "Asus Prime H610m-k Ddr4 1700 12°gen 2", price: 150000, category:"motherboard", description:"escubre el poder y la eficiencia de la Motherboard Asus Prime H610M-K D4, diseñada especialmente para procesadores Intel de socket 1700. Esta placa madre de alta calidad te permitirá armar una PC potente y confiable, ideal para el trabajo, el estudio o el entretenimiento. Con una capacidad máxima de 64 GB de memoria RAM DDR4, podrás disfrutar de un rendimiento fluido y rápido en todas tus tareas. Además, su chipset H610 garantiza una excelente compatibilidad y estabilidad en el sistema. No esperes más para experimentar la calidad y el rendimiento que solo Asus Prime puede ofrecerte en Argentina.", image: "https://http2.mlstatic.com/D_NQ_NP_645944-MLA74129732817_012024-O.webp"},
    { id: 9, name: "Asus Prime B760m-a Wifi D4 Intel Lga1700", price: 290000, category:"motherboard", description:"Intel® Socket LGA1700 para procesadores Intel® Core™ de 14. a y 13. a generación, Intel® Core™ de 12. a generación, Pentium® Gold y Celeron® Conjunto de chips Intel® B760.", image: "https://http2.mlstatic.com/D_NQ_NP_727041-MLU75993717470_052024-O.webp"},
    { id: 10, name: "Gigabyte Z790 A Elite Ax Ice D5 1700 Atx Color Blanco", price: 690000, category:"motherboard", description:"as placas base para juegos de la serie AORUS Z790 optimizan el rendimiento de los últimos procesadores Intel de 13.ª generación con diseño de energía digital. La solución térmica totalmente metálica maneja el calor generado. Camino ultrarrápido hacia el PCIe 5.0 y compatibilidad con la memoria DDR5.", image: "https://http2.mlstatic.com/D_NQ_NP_927061-MLU74464218679_022024-O.webp"}
];

export const getProducts = new Promise((resolve) => {
    setTimeout(() => {
        resolve(products);
    }, 2000);
});

export const getProduct = (id) => {
    return products.find((prod) => prod.id == id);
};

export const getCategory = (category) => {
    return products.filter((product) => product.category === category);
};